<?php

namespace Database\Seeders\KMJ;

use App\Models\Models\KMJ\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountryRegionDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG', 'regions' => []],
            ['name' => 'Albania', 'code' => 'ALB', 'regions' => []],
            ['name' => 'Algeria', 'code' => 'DZA', 'regions' => []],
            ['name' => 'American Samoa', 'code' => 'ASM', 'regions' => []],
            ['name' => 'Andorra', 'code' => 'AND', 'regions' => []],
            ['name' => 'Angola', 'code' => 'AGO', 'regions' => []],
            ['name' => 'Anguilla', 'code' => 'AIA', 'regions' => []],
            ['name' => 'Antarctica', 'code' => 'ATA', 'regions' => []],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG', 'regions' => []],
            ['name' => 'Argentina', 'code' => 'ARG', 'regions' => []],
            ['name' => 'Armenia', 'code' => 'ARM', 'regions' => []],
            ['name' => 'Aruba', 'code' => 'ABW', 'regions' => []],
            ['name' => 'Australia', 'code' => 'AUS', 'regions' => []],
            ['name' => 'Austria', 'code' => 'AUT', 'regions' => []],
            ['name' => 'Azerbaijan', 'code' => 'AZE', 'regions' => []],
            ['name' => 'Bahamas (the)', 'code' => 'BHS', 'regions' => []],
            ['name' => 'Bahrain', 'code' => 'BHR', 'regions' => []],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'regions' => []],
            ['name' => 'Barbados', 'code' => 'BRB', 'regions' => []],
            ['name' => 'Belarus', 'code' => 'BLR', 'regions' => []],
            ['name' => 'Belgium', 'code' => 'BEL', 'regions' => []],
            ['name' => 'Belize', 'code' => 'BLZ', 'regions' => []],
            ['name' => 'Benin', 'code' => 'BEN', 'regions' => []],
            ['name' => 'Bermuda', 'code' => 'BMU', 'regions' => []],
            ['name' => 'Bhutan', 'code' => 'BTN', 'regions' => []],
            ['name' => 'Bolivia (Plurinational State of)', 'code' => 'BOL', 'regions' => []],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BES', 'regions' => []],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'regions' => []],
            ['name' => 'Botswana', 'code' => 'BWA', 'regions' => []],
            ['name' => 'Bouvet Island', 'code' => 'BVT', 'regions' => []],
            ['name' => 'Brazil', 'code' => 'BRA', 'regions' => []],
            ['name' => 'British Indian Ocean Territory (the)', 'code' => 'IOT', 'regions' => []],
            ['name' => 'Brunei Darussalam', 'code' => 'BRN', 'regions' => []],
            ['name' => 'Bulgaria', 'code' => 'BGR', 'regions' => []],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'regions' => []],
            ['name' => 'Burundi', 'code' => 'BDI', 'regions' => []],
            ['name' => 'Cabo Verde', 'code' => 'CPV', 'regions' => []],
            ['name' => 'Cambodia', 'code' => 'KHM', 'regions' => []],
            ['name' => 'Cameroon', 'code' => 'CMR', 'regions' => []],
            ['name' => 'Canada', 'code' => 'CAN', 'regions' => []],
            ['name' => 'Cayman Islands (the)', 'code' => 'CYM', 'regions' => []],
            ['name' => 'Central African Republic (the)', 'code' => 'CAF', 'regions' => []],
            ['name' => 'Chad', 'code' => 'TCD', 'regions' => []],
            ['name' => 'Chile', 'code' => 'CHL', 'regions' => []],
            ['name' => 'China', 'code' => 'CHN', 'regions' => []],
            ['name' => 'Christmas Island', 'code' => 'CXR', 'regions' => []],
            ['name' => 'Cocos (Keeling) Islands (the)', 'code' => 'CCK', 'regions' => []],
            ['name' => 'Colombia', 'code' => 'COL', 'regions' => []],
            ['name' => 'Comoros (the)', 'code' => 'COM', 'regions' => []],
            ['name' => 'Congo (the Democratic Republic of the)', 'code' => 'COD', 'regions' => []],
            ['name' => 'Congo (the)', 'code' => 'COG', 'regions' => []],
            ['name' => 'Cook Islands (the)', 'code' => 'COK', 'regions' => []],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'regions' => []],
            ['name' => 'Croatia', 'code' => 'HRV', 'regions' => []],
            ['name' => 'Cuba', 'code' => 'CUB', 'regions' => []],
            ['name' => 'Curaçao', 'code' => 'CUW', 'regions' => []],
            ['name' => 'Cyprus', 'code' => 'CYP', 'regions' => []],
            ['name' => 'Czechia', 'code' => 'CZE', 'regions' => []],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV', 'regions' => []],
            ['name' => 'Denmark', 'code' => 'DNK', 'regions' => []],
            ['name' => 'Djibouti', 'code' => 'DJI', 'regions' => []],
            ['name' => 'Dominica', 'code' => 'DMA', 'regions' => []],
            ['name' => 'Dominican Republic (the)', 'code' => 'DOM', 'regions' => []],
            ['name' => 'Ecuador', 'code' => 'ECU', 'regions' => []],
            ['name' => 'Egypt', 'code' => 'EGY', 'regions' => []],
            ['name' => 'El Salvador', 'code' => 'SLV', 'regions' => []],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'regions' => []],
            ['name' => 'Eritrea', 'code' => 'ERI', 'regions' => []],
            ['name' => 'Estonia', 'code' => 'EST', 'regions' => []],
            ['name' => 'Eswatini', 'code' => 'SWZ', 'regions' => []],
            ['name' => 'Ethiopia', 'code' => 'ETH', 'regions' => []],
            ['name' => 'Falkland Islands (the) [Malvinas]', 'code' => 'FLK', 'regions' => []],
            ['name' => 'Faroe Islands (the)', 'code' => 'FRO', 'regions' => []],
            ['name' => 'Fiji', 'code' => 'FJI', 'regions' => []],
            ['name' => 'Finland', 'code' => 'FIN', 'regions' => []],
            ['name' => 'France', 'code' => 'FRA', 'regions' => []],
            ['name' => 'French Guiana', 'code' => 'GUF', 'regions' => []],
            ['name' => 'French Polynesia', 'code' => 'PYF', 'regions' => []],
            ['name' => 'French Southern Territories (the)', 'code' => 'ATF', 'regions' => []],
            ['name' => 'Gabon', 'code' => 'GAB', 'regions' => []],
            ['name' => 'Gambia (the)', 'code' => 'GMB', 'regions' => []],
            ['name' => 'Georgia', 'code' => 'GEO', 'regions' => []],
            ['name' => 'Germany', 'code' => 'DEU', 'regions' => []],
            ['name' => 'Ghana', 'code' => 'GHA', 'regions' => []],
            ['name' => 'Gibraltar', 'code' => 'GIB', 'regions' => []],
            ['name' => 'Greece', 'code' => 'GRC', 'regions' => []],
            ['name' => 'Greenland', 'code' => 'GRL', 'regions' => []],
            ['name' => 'Grenada', 'code' => 'GRD', 'regions' => []],
            ['name' => 'Guadeloupe', 'code' => 'GLP', 'regions' => []],
            ['name' => 'Guam', 'code' => 'GUM', 'regions' => []],
            ['name' => 'Guatemala', 'code' => 'GTM', 'regions' => []],
            ['name' => 'Guernsey', 'code' => 'GGY', 'regions' => []],
            ['name' => 'Guinea', 'code' => 'GIN', 'regions' => []],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'regions' => []],
            ['name' => 'Guyana', 'code' => 'GUY', 'regions' => []],
            ['name' => 'Haiti', 'code' => 'HTI', 'regions' => []],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HMD', 'regions' => []],
            ['name' => 'Holy See (the)', 'code' => 'VAT', 'regions' => []],
            ['name' => 'Honduras', 'code' => 'HND', 'regions' => []],
            ['name' => 'Hong Kong', 'code' => 'HKG', 'regions' => []],
            ['name' => 'Hungary', 'code' => 'HUN', 'regions' => []],
            ['name' => 'Iceland', 'code' => 'ISL', 'regions' => []],
            ['name' => 'India', 'code' => 'IND', 'regions' => []],
            ['name' => 'Indonesia', 'code' => 'IDN', 'regions' => []],
            ['name' => 'Iran (Islamic Republic of)', 'code' => 'IRN', 'regions' => []],
            ['name' => 'Iraq', 'code' => 'IRQ', 'regions' => []],
            ['name' => 'Ireland', 'code' => 'IRL', 'regions' => []],
            ['name' => 'Isle of Man', 'code' => 'IMN', 'regions' => []],
            ['name' => 'Israel', 'code' => 'ISR', 'regions' => []],
            ['name' => 'Italy', 'code' => 'ITA', 'regions' => []],
            ['name' => 'Jamaica', 'code' => 'JAM', 'regions' => []],
            ['name' => 'Japan', 'code' => 'JPN', 'regions' => []],
            ['name' => 'Jersey', 'code' => 'JEY', 'regions' => []],
            ['name' => 'Jordan', 'code' => 'JOR', 'regions' => []],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'regions' => []],
            ['name' => 'Kenya', 'code' => 'KEN', 'regions' => []],
            ['name' => 'Kiribati', 'code' => 'KIR', 'regions' => []],
            ['name' => 'Korea (the Democratic People\'s Republic of)', 'code' => 'PRK', 'regions' => []],
            ['name' => 'Korea (the Republic of)', 'code' => 'KOR', 'regions' => []],
            ['name' => 'Kuwait', 'code' => 'KWT', 'regions' => []],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'regions' => []],
            ['name' => 'Lao People\'s Democratic Republic (the)', 'code' => 'LAO', 'regions' => []],
            ['name' => 'Latvia', 'code' => 'LVA', 'regions' => []],
            ['name' => 'Lebanon', 'code' => 'LBN', 'regions' => []],
            ['name' => 'Lesotho', 'code' => 'LSO', 'regions' => []],
            ['name' => 'Liberia', 'code' => 'LBR', 'regions' => []],
            ['name' => 'Libya', 'code' => 'LBY', 'regions' => []],
            ['name' => 'Liechtenstein', 'code' => 'LIE', 'regions' => []],
            ['name' => 'Lithuania', 'code' => 'LTU', 'regions' => []],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'regions' => []],
            ['name' => 'Macao', 'code' => 'MAC', 'regions' => []],
            ['name' => 'Madagascar', 'code' => 'MDG', 'regions' => []],
            ['name' => 'Malawi', 'code' => 'MWI', 'regions' => []],
            ['name' => 'Malaysia', 'code' => 'MYS', 'regions' => []],
            ['name' => 'Maldives', 'code' => 'MDV', 'regions' => []],
            ['name' => 'Mali', 'code' => 'MLI', 'regions' => []],
            ['name' => 'Malta', 'code' => 'MLT', 'regions' => []],
            ['name' => 'Marshall Islands (the)', 'code' => 'MHL', 'regions' => []],
            ['name' => 'Martinique', 'code' => 'MTQ', 'regions' => []],
            ['name' => 'Mauritania', 'code' => 'MRT', 'regions' => []],
            ['name' => 'Mauritius', 'code' => 'MUS', 'regions' => []],
            ['name' => 'Mayotte', 'code' => 'MYT', 'regions' => []],
            ['name' => 'Mexico', 'code' => 'MEX', 'regions' => []],
            ['name' => 'Micronesia (Federated States of)', 'code' => 'FSM', 'regions' => []],
            ['name' => 'Moldova (the Republic of)', 'code' => 'MDA', 'regions' => []],
            ['name' => 'Monaco', 'code' => 'MCO', 'regions' => []],
            ['name' => 'Mongolia', 'code' => 'MNG', 'regions' => []],
            ['name' => 'Montenegro', 'code' => 'MNE', 'regions' => []],
            ['name' => 'Montserrat', 'code' => 'MSR', 'regions' => []],
            ['name' => 'Morocco', 'code' => 'MAR', 'regions' => []],
            ['name' => 'Mozambique', 'code' => 'MOZ', 'regions' => []],
            ['name' => 'Myanmar', 'code' => 'MMR', 'regions' => []],
            ['name' => 'Namibia', 'code' => 'NAM', 'regions' => []],
            ['name' => 'Nauru', 'code' => 'NRU', 'regions' => []],
            ['name' => 'Nepal', 'code' => 'NPL', 'regions' => []],
            ['name' => 'Netherlands (the)', 'code' => 'NLD', 'regions' => []],
            ['name' => 'New Caledonia', 'code' => 'NCL', 'regions' => []],
            ['name' => 'New Zealand', 'code' => 'NZL', 'regions' => []],
            ['name' => 'Nicaragua', 'code' => 'NIC', 'regions' => []],
            ['name' => 'Niger (the)', 'code' => 'NER', 'regions' => []],
            ['name' => 'Nigeria', 'code' => 'NGA', 'regions' => []],
            ['name' => 'Niue', 'code' => 'NIU', 'regions' => []],
            ['name' => 'Norfolk Island', 'code' => 'NFK', 'regions' => []],
            ['name' => 'Northern Mariana Islands (the)', 'code' => 'MNP', 'regions' => []],
            ['name' => 'Norway', 'code' => 'NOR', 'regions' => []],
            ['name' => 'Oman', 'code' => 'OMN', 'regions' => []],
            ['name' => 'Pakistan', 'code' => 'PAK', 'regions' => []],
            ['name' => 'Palau', 'code' => 'PLW', 'regions' => []],
            ['name' => 'Palestine, State of', 'code' => 'PSE', 'regions' => []],
            ['name' => 'Panama', 'code' => 'PAN', 'regions' => []],
            ['name' => 'Papua New Guinea', 'code' => 'PNG', 'regions' => []],
            ['name' => 'Paraguay', 'code' => 'PRY', 'regions' => []],
            ['name' => 'Peru', 'code' => 'PER', 'regions' => []],
            ['name' => 'Philippines (the)', 'code' => 'PHL', 'regions' => []],
            ['name' => 'Pitcairn', 'code' => 'PCN', 'regions' => []],
            ['name' => 'Poland', 'code' => 'POL', 'regions' => []],
            ['name' => 'Portugal', 'code' => 'PRT', 'regions' => []],
            ['name' => 'Puerto Rico', 'code' => 'PRI', 'regions' => []],
            ['name' => 'Qatar', 'code' => 'QAT', 'regions' => []],
            ['name' => 'Republic of North Macedonia', 'code' => 'MKD', 'regions' => []],
            ['name' => 'Romania', 'code' => 'ROU', 'regions' => []],
            ['name' => 'Russian Federation (the)', 'code' => 'RUS', 'regions' => []],
            ['name' => 'Rwanda', 'code' => 'RWA', 'regions' => []],
            ['name' => 'Réunion', 'code' => 'REU', 'regions' => []],
            ['name' => 'Saint Barthélemy', 'code' => 'BLM', 'regions' => []],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SHN', 'regions' => []],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'regions' => []],
            ['name' => 'Saint Lucia', 'code' => 'LCA', 'regions' => []],
            ['name' => 'Saint Martin (French part)', 'code' => 'MAF', 'regions' => []],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM', 'regions' => []],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'regions' => []],
            ['name' => 'Samoa', 'code' => 'WSM', 'regions' => []],
            ['name' => 'San Marino', 'code' => 'SMR', 'regions' => []],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP', 'regions' => []],
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'regions' => []],
            ['name' => 'Senegal', 'code' => 'SEN', 'regions' => []],
            ['name' => 'Serbia', 'code' => 'SRB', 'regions' => []],
            ['name' => 'Seychelles', 'code' => 'SYC', 'regions' => []],
            ['name' => 'Sierra Leone', 'code' => 'SLE', 'regions' => []],
            ['name' => 'Singapore', 'code' => 'SGP', 'regions' => []],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SXM', 'regions' => []],
            ['name' => 'Slovakia', 'code' => 'SVK', 'regions' => []],
            ['name' => 'Slovenia', 'code' => 'SVN', 'regions' => []],
            ['name' => 'Solomon Islands', 'code' => 'SLB', 'regions' => []],
            ['name' => 'Somalia', 'code' => 'SOM', 'regions' => []],
            ['name' => 'South Africa', 'code' => 'ZAF', 'regions' => []],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SGS', 'regions' => []],
            ['name' => 'South Sudan', 'code' => 'SSD', 'regions' => []],
            ['name' => 'Spain', 'code' => 'ESP', 'regions' => []],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'regions' => []],
            ['name' => 'Sudan (the)', 'code' => 'SDN', 'regions' => []],
            ['name' => 'Suriname', 'code' => 'SUR', 'regions' => []],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJM', 'regions' => []],
            ['name' => 'Sweden', 'code' => 'SWE', 'regions' => []],
            ['name' => 'Switzerland', 'code' => 'CHE', 'regions' => []],
            ['name' => 'Syrian Arab Republic', 'code' => 'SYR', 'regions' => []],
            ['name' => 'Taiwan (Province of China)', 'code' => 'TWN', 'regions' => []],
            ['name' => 'Tajikistan', 'code' => 'TJK', 'regions' => []],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZA',  'regions' => [
                [
                    'name' => 'Dar es Salaam',
                    'code' => '10000',
                    'districts' => [
                        ['name' => 'Ilala', 'code' => '11000'],
                        ['name' => 'Kigamboni', 'code' => '12000'],
                        ['name' => 'Ubungo', 'code' => '13000'],
                        ['name' => 'Kinondoni', 'code' => '14000'],
                        ['name' => 'Temeke', 'code' => '15000'],
                    ],
                ],
                [
                    'name' => 'Tanga',
                    'code' => '21000',
                    'districts' => [
                        ['name' => 'Tanga CBD', 'code' => '21100'],
                        ['name' => 'Tanga', 'code' => '21200'],
                        ['name' => 'Pangani', 'code' => '21300'],
                        ['name' => 'Muheza', 'code' => '21400'],
                        ['name' => 'Mkinga', 'code' => '21500'],
                        ['name' => 'Korogwe', 'code' => '21600'],
                        ['name' => 'Lushoto', 'code' => '21700'],
                        ['name' => 'Handeni', 'code' => '21800'],
                        ['name' => 'Kilindi', 'code' => '21900'],
                    ],
                ],
                [
                    'name' => 'Arusha',
                    'code' => '23000',
                    'districts' => [
                        ['name' => 'Arusha CBD', 'code' => '23100'],
                        ['name' => 'Arusha', 'code' => '23200'],
                        ['name' => 'Arumeru', 'code' => '23300'],
                        ['name' => 'Monduli', 'code' => '23400'],
                        ['name' => 'Longido', 'code' => '23500'],
                        ['name' => 'Karatu', 'code' => '23600'],
                        ['name' => 'Ngorongoro', 'code' => '23700'],
                    ],
                ],
                [
                    'name' => 'Kilimanjaro',
                    'code' => '25000',
                    'districts' => [
                        ['name' => 'Moshi CBD', 'code' => '25100'],
                        ['name' => 'Moshi', 'code' => '25200'],
                        ['name' => 'Hai', 'code' => '25300'],
                        ['name' => 'Siha', 'code' => '25400'],
                        ['name' => 'Mwanga', 'code' => '25500'],
                        ['name' => 'Same', 'code' => '25600'],
                        ['name' => 'Rombo', 'code' => '25700'],
                    ],
                ],
                [
                    'name' => 'Manyara',
                    'code' => '27000',
                    'districts' => [
                        ['name' => 'Babati CBD', 'code' => '27100'],
                        ['name' => 'Babati', 'code' => '27200'],
                        ['name' => 'Hanang', 'code' => '27300'],
                        ['name' => 'Mbulu', 'code' => '27400'],
                        ['name' => 'Kiteto', 'code' => '27500'],
                        ['name' => 'Simanjiro', 'code' => '27600'],
                    ],
                ],
                [
                    'name' => 'Geita',
                    'code' => '30000',
                    'districts' => [
                        ['name' => 'Geita', 'code' => '30100'],
                        ['name' => "Nyang'wale", 'code' => '30200'],
                        ['name' => 'Chato', 'code' => '30300'],
                        ['name' => 'Mbogwe', 'code' => '30400'],
                        ['name' => 'Bukombe', 'code' => '30500'],
                    ],
                ],
                [
                    'name' => 'Mara',
                    'code' => '31000',
                    'districts' => [
                        ['name' => 'Musoma CBD', 'code' => '31100'],
                        ['name' => 'Butiama', 'code' => '31200'],
                        ['name' => 'Rorya', 'code' => '31300'],
                        ['name' => 'Tarime', 'code' => '31400'],
                        ['name' => 'Bunda', 'code' => '31500'],
                        ['name' => 'Serengeti', 'code' => '31600'],
                        ['name' => 'Musoma Town', 'code' => '31700'],
                    ],
                ],
                [
                    'name' => 'Mwanza',
                    'code' => '33000',
                    'districts' => [
                        ['name' => 'Nyamagana', 'code' => '33100'],
                        ['name' => 'Ilemela', 'code' => '33200'],
                        ['name' => 'Sengerema', 'code' => '33300'],
                        ['name' => 'Magu', 'code' => '33400'],
                        ['name' => 'Misungwi', 'code' => '33500'],
                        ['name' => 'Ukerewe', 'code' => '33600'],
                        ['name' => 'Kwimba', 'code' => '33800'],
                    ],
                ],
                [
                    'name' => 'Kagera',
                    'code' => '35000',
                    'districts' => [
                        ['name' => 'Bukoba', 'code' => '35200'],
                        ['name' => 'Bukoba Rural', 'code' => '35100'],
                        ['name' => 'Missenyi', 'code' => '35300'],
                        ['name' => 'Karagwe', 'code' => '35400'],
                        ['name' => 'Muleba', 'code' => '35500'],
                        ['name' => 'Biharamulo', 'code' => '35600'],
                        ['name' => 'Ngara', 'code' => '35700'],
                        ['name' => 'Kyerwa', 'code' => '35800'],
                    ],
                ],
                [
                    'name' => 'Shinyanga',
                    'code' => '37000',
                    'districts' => [
                        ['name' => 'Shinyanga CBD', 'code' => '37100'],
                        ['name' => 'Shinyanga', 'code' => '37200'],
                        ['name' => 'Kahama CBD', 'code' => '37300'],
                        ['name' => 'Kahama', 'code' => '37400'],
                        ['name' => 'Kishapu', 'code' => '37500'],
                    ],
                ],
                [
                    'name' => 'Simiyu',
                    'code' => '39000',
                    'districts' => [
                        ['name' => 'Bariadi', 'code' => '39100'],
                        ['name' => 'Itilima', 'code' => '39200'],
                        ['name' => 'Maswa', 'code' => '39300'],
                        ['name' => 'Meatu', 'code' => '39400'],
                        ['name' => 'Busega', 'code' => '39500'],
                    ],
                ],
                [
                    'name' => 'Dodoma',
                    'code' => '41000',
                    'districts' => [
                        ['name' => 'Dodoma CBD', 'code' => '41100'],
                        ['name' => 'Dodoma', 'code' => '41200'],
                        ['name' => 'Bahi', 'code' => '41300'],
                        ['name' => 'Chamwino', 'code' => '41400'],
                        ['name' => 'Kongwa', 'code' => '41500'],
                        ['name' => 'Mpwapwa', 'code' => '41600'],
                        ['name' => 'Kondoa', 'code' => '41700'],
                        ['name' => 'Chemba', 'code' => '41800'],
                    ],
                ],
                [
                    'name' => 'Singida',
                    'code' => '43000',
                    'districts' => [
                        ['name' => 'Singida CBD', 'code' => '43100'],
                        ['name' => 'Singida', 'code' => '43200'],
                        ['name' => 'Iramba', 'code' => '43300'],
                        ['name' => 'Manyoni', 'code' => '43400'],
                        ['name' => 'Mkalama', 'code' => '43500'],
                        ['name' => 'Ikungi', 'code' => '43600'],
                    ],
                ],
                [
                    'name' => 'Tabora',
                    'code' => '45000',
                    'districts' => [
                        ['name' => 'Tabora CBD', 'code' => '45100'],
                        ['name' => 'Uyui', 'code' => '45200'],
                        ['name' => 'Sikonge', 'code' => '45300'],
                        ['name' => 'Nzega', 'code' => '45400'],
                        ['name' => 'Urambo', 'code' => '45500'],
                        ['name' => 'Igunga', 'code' => '45600'],
                        ['name' => 'Kaliua', 'code' => '45700'],
                    ],
                ],
                [
                    'name' => 'Kigoma',
                    'code' => '47000',
                    'districts' => [
                        ['name' => 'Kigoma CBD', 'code' => '47100'],
                        ['name' => 'Kigoma', 'code' => '47200'],
                        ['name' => 'Kasulu', 'code' => '47300'],
                        ['name' => 'Kibondo', 'code' => '47400'],
                        ['name' => 'Buhigwe', 'code' => '47500'],
                        ['name' => 'Uvinza', 'code' => '47600'],
                        ['name' => 'Kakonko', 'code' => '47700'],
                    ],
                ],
                [
                    'name' => 'Katavi',
                    'code' => '50000',
                    'districts' => [
                        ['name' => 'Mpanda CBD', 'code' => '50100'],
                        ['name' => 'Mpanda', 'code' => '50200'],
                        ['name' => 'Mlele', 'code' => '50300'],
                    ],
                ],
                [
                    'name' => 'Iringa',
                    'code' => '51000',
                    'districts' => [
                        ['name' => 'Iringa CBD', 'code' => '51100'],
                        ['name' => 'Iringa', 'code' => '51200'],
                        ['name' => 'Kilolo', 'code' => '51300'],
                        ['name' => 'Mufindi', 'code' => '51400'],
                    ],
                ],
                [
                    'name' => 'Mbeya',
                    'code' => '53000',
                    'districts' => [
                        ['name' => 'Mbeya CBD', 'code' => '53100'],
                        ['name' => 'Mbeya', 'code' => '53200'],
                        ['name' => 'Mbozi', 'code' => '53300'],
                        ['name' => 'Ileje', 'code' => '53400'],
                        ['name' => 'Rungwe', 'code' => '53500'],
                        ['name' => 'Mbarali', 'code' => '53600'],
                        ['name' => 'Kyela', 'code' => '53700'],
                        ['name' => 'Chunya', 'code' => '53800'],
                        ['name' => 'Momba', 'code' => '53900'],
                    ],
                ],
                [
                    'name' => 'Rukwa',
                    'code' => '55000',
                    'districts' => [
                        ['name' => 'Sumbawanga CBD', 'code' => '55100'],
                        ['name' => 'Sumbawanga', 'code' => '55200'],
                        ['name' => 'Nkasi', 'code' => '55300'],
                        ['name' => 'Kalambo', 'code' => '55400'],
                    ],
                ],
                [
                    'name' => 'Ruvuma',
                    'code' => '57000',
                    'districts' => [
                        ['name' => 'Songea CBD', 'code' => '57100'],
                        ['name' => 'Songea', 'code' => '57200'],
                        ['name' => 'Namtumbo', 'code' => '57300'],
                        ['name' => 'Mbinga', 'code' => '57400'],
                        ['name' => 'Nyasa', 'code' => '57500'],
                        ['name' => 'Tunduru', 'code' => '57600'],
                    ],
                ],
                [
                    'name' => 'Njombe',
                    'code' => '59000',
                    'districts' => [
                        ['name' => 'Njombe CBD', 'code' => '59100'],
                        ['name' => 'Njombe', 'code' => '59200'],
                        ['name' => "Wanging'ombe", 'code' => '59300'],
                        ['name' => 'Ludewa', 'code' => '59400'],
                        ['name' => 'Makete', 'code' => '59500'],
                    ],
                ],
                [
                    'name' => 'Pwani',
                    'code' => '61000',
                    'districts' => [
                        ['name' => 'Kibaha CBD', 'code' => '61100'],
                        ['name' => 'Kibaha', 'code' => '61200'],
                        ['name' => 'Bagamoyo', 'code' => '61300'],
                        ['name' => 'Kisarawe', 'code' => '61400'],
                        ['name' => 'Mkuranga', 'code' => '61500'],
                        ['name' => 'Rufiji', 'code' => '61600'],
                        ['name' => 'Mafia', 'code' => '61700'],
                    ],
                ],
                [
                    'name' => 'Mtwara',
                    'code' => '63000',
                    'districts' => [
                        ['name' => 'Mtwara CBD', 'code' => '63100'],
                        ['name' => 'Mtwara', 'code' => '63200'],
                        ['name' => 'Tandahimba', 'code' => '63300'],
                        ['name' => 'Newala', 'code' => '63400'],
                        ['name' => 'Masasi', 'code' => '63500'],
                        ['name' => 'Nanyumbu', 'code' => '63600'],
                    ],
                ],
                [
                    'name' => 'Lindi',
                    'code' => '65000',
                    'districts' => [
                        ['name' => 'Lindi CBD', 'code' => '65100'],
                        ['name' => 'Lindi Rural', 'code' => '65200'],
                        ['name' => 'Nachingwea', 'code' => '65300'],
                        ['name' => 'Kilwa', 'code' => '65400'],
                        ['name' => 'Liwale', 'code' => '65500'],
                        ['name' => 'Ruangwa', 'code' => '65600'],
                    ],
                ],
                [
                    'name' => 'Morogoro',
                    'code' => '67000',
                    'districts' => [
                        ['name' => 'Morogoro CBD', 'code' => '67100'],
                        ['name' => 'Morogoro', 'code' => '67200'],
                        ['name' => 'Mvomero', 'code' => '67300'],
                        ['name' => 'Kilosa', 'code' => '67400'],
                        ['name' => 'Kilombero', 'code' => '67500'],
                        ['name' => 'Ulanga', 'code' => '67600'],
                        ['name' => 'Gairo', 'code' => '67700'],
                    ],
                ],
                [
                    'name' => 'Unguja Magharibi',
                    'code' => '71000',
                    'districts' => [
                        ['name' => 'Mjini', 'code' => '71100'],
                        ['name' => 'Magharibi', 'code' => '71200'],
                    ],
                ],
                [
                    'name' => 'Zanzibar Kati / Kusini',
                    'code' => '72000',
                    'districts' => [
                        ['name' => 'Kusini', 'code' => '72100'],
                        ['name' => 'Kati', 'code' => '72200'],
                    ],
                ],
                [
                    'name' => 'Unguja Kaskazini',
                    'code' => '73000',
                    'districts' => [
                        ['name' => 'Kaskazini A', 'code' => '73100'],
                        ['name' => 'Kaskazini B', 'code' => '73200'],
                    ],
                ],
                [
                    'name' => 'Pemba Kusini',
                    'code' => '74000',
                    'districts' => [
                        ['name' => 'Mkoani', 'code' => '74100'],
                        ['name' => 'Chakechake', 'code' => '74200'],
                    ],
                ],
                [
                    'name' => 'Pemba Kaskazini',
                    'code' => '75000',
                    'districts' => [
                        ['name' => 'Wete', 'code' => '75100'],
                        ['name' => 'Micheweni', 'code' => '75200'],
                    ],
                ],
            ],],
            ['name' => 'Thailand', 'code' => 'THA', 'regions' => []],
            ['name' => 'Timor-Leste', 'code' => 'TLS', 'regions' => []],
            ['name' => 'Togo', 'code' => 'TGO', 'regions' => []],
            ['name' => 'Tokelau', 'code' => 'TKL', 'regions' => []],
            ['name' => 'Tonga', 'code' => 'TON', 'regions' => []],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'regions' => []],
            ['name' => 'Tunisia', 'code' => 'TUN', 'regions' => []],
            ['name' => 'Turkey', 'code' => 'TUR', 'regions' => []],
            ['name' => 'Turkmenistan', 'code' => 'TKM', 'regions' => []],
            ['name' => 'Tuvalu', 'code' => 'TUV', 'regions' => []],
            ['name' => 'Uganda', 'code' => 'UGA', 'regions' => []],
            ['name' => 'Ukraine', 'code' => 'UKR', 'regions' => []],
            ['name' => 'United Arab Emirates (the)', 'code' => 'ARE', 'regions' => []],
            ['name' => 'United Kingdom of Great Britain and Northern Ireland (the)', 'code' => 'GBR', 'regions' => []],
            ['name' => 'United States Minor Outlying Islands (the)', 'code' => 'UMI', 'regions' => []],
            ['name' => 'United States of America (the)', 'code' => 'USA', 'regions' => []],
            ['name' => 'Uruguay', 'code' => 'URY', 'regions' => []],
            ['name' => 'Uzbekistan', 'code' => 'UZB', 'regions' => []],
            ['name' => 'Vanuatu', 'code' => 'VUT', 'regions' => []],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'code' => 'VEN', 'regions' => []],
            ['name' => 'Viet Nam', 'code' => 'VNM', 'regions' => []],
            ['name' => 'Virgin Islands (British)', 'code' => 'VGB', 'regions' => []],
            ['name' => 'Virgin Islands (U.S.)', 'code' => 'VIR', 'regions' => []],
            ['name' => 'Western Sahara', 'code' => 'ESH', 'regions' => []],
            ['name' => 'Yemen', 'code' => 'YEM', 'regions' => []],
            ['name' => 'Zambia', 'code' => 'ZMB', 'regions' => []],
            ['name' => 'Zimbabwe', 'code' => 'ZWE', 'regions' => []],
        ];

        foreach ($countries as $countryData) {
            $regionsData = $countryData['regions'] ?? [];
            unset($countryData['regions']);

            $country = Country::create($countryData);

            foreach ($regionsData as $regionData) {
                $districtsData = $regionData['districts'] ?? [];
                unset($regionData['districts']);

                $region = $country->regions()->create($regionData);

                foreach ($districtsData as $districtData) {
                    $region->districts()->create($districtData);
                }
            }
        }
    }
}
